version: '3.9'

services:
  nuxt:
    container_name: nuxt
    build:
      context: .
      dockerfile: docker/nuxt/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    user: "node"
    volumes:
      - ./app:/app:cached
      - nuxt_node_modules:/app/node_modules
      - ./.vscode:/app/.vscode
    ports:
      - "3000:3000"
      - "24678:24678"
    tty: true
    environment:
      - HOST=0.0.0.0
      - port=3000
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "yarn && yarn dev"
volumes:
  nuxt_node_modules:
